### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by sejomagno** [cvalenzuela/Mappa#4]
I just read [your post](https://medium.com/@ProcessingOrg/maps-maps-maps-f0914218c87b) in the Processing Foundation blog. I think this project is very cool. I'm looking at some of the tutorials and they appear to be very complete. Will definitely use as a resource and reference. Congrats and thank you!

**Comment by cvalenzuela** [comment]
thanks @sejomagno, that's really nice!
I still need to finish some tutorials and resources but let me know how it works for you!

**Comment by BenjaminHabert** [comment]
Yes, thanks for creating this!

I am currently using d3 svg overlays on top of leaflet maps to show geojson objects (static and moving objects). For which use-cases do you reckon the p5-canvas-approach would be more suitable ? 

I haven't looked properly at the doc yet but it seems that the map needs to be built by Mappa. Can you reference an existing map that is already sitting in the dom ?

**Comment by cvalenzuela** [comment]
I think it's more suitable when you want to add more interactivity to your maps because you can use the complete p5 library with it. But if you are just displaying static pins perhaps the leaflet/d3 approach is enough. 

Mappa just binds the p5 canvas to a div containing the map. [Here](https://cvalenzuela.github.io/Mappa/examples/tile/Leaflet/) is a demo working with leaflet.
Check out the demos for using other maps libraries.
